// Final draft 5 (D-083): draft 2's content in new layouts, generated by scripts/build-page.js.
// The page has no Lab script; the few interactions are here. Particles dim under text (D-079).
import '@fontsource/instrument-serif/400.css'
import '@fontsource/instrument-serif/400-italic.css'
import '@fontsource/inter/400.css'
import '@fontsource/inter/500.css'
import '@fontsource/inter/600.css'
import '@fontsource/jetbrains-mono/400.css'
import '@fontsource/jetbrains-mono/500.css'
import '../../dala-lab-engine/engine.css'
import '../../dala-lab-engine/final.css'
import './style.css'
import * as shapes from './config.js'
import EXTENTS from './extents.json'
import { startStage } from '../../dala-lab-engine/stage.js'

const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)]
const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches

// hero: the industry word types out and deletes, as in drafts 2 to 4
const ROT = ['staffing firms', 'clinics', 'acquirers', 'service businesses', 'operators']
if (!reduced) {
  const rot = $('#rotor'), out = rot.firstElementChild
  rot.classList.add('typing')
  let ri = 0, n = ROT[0].length, dir = -1
  const tick = () => {
    n += dir
    if (n < 0) { ri = (ri + 1) % ROT.length; n = 0; dir = 1 }
    out.textContent = ROT[ri].slice(0, n)
    if (dir > 0 && n === ROT[ri].length) { dir = -1; return setTimeout(tick, 1900) }
    setTimeout(tick, dir > 0 ? 85 : 40)
  }
  setTimeout(tick, 2200)
}

// header bar darkens once the page scrolls
const bar = $('.topbar')
const onScroll = () => bar.classList.toggle('scrolled', scrollY > 8)
addEventListener('scroll', onScroll, { passive: true }); onScroll()

// what we build: each row's picture runs only while it is on screen (final.css .in)
const io = new IntersectionObserver(es => { for (const e of es) e.target.classList.toggle('in', e.isIntersecting) }, { threshold: 0.3 })
for (const el of $$('.ix-row')) io.observe(el)

// proof: filter the ledger by group
for (const b of $$('#work .tabs button')) b.addEventListener('click', () => {
  for (const x of $$('#work .tabs button')) { x.classList.toggle('on', x === b); x.setAttribute('aria-pressed', x === b) }
  for (const r of $$('#work tbody tr')) r.hidden = b.dataset.f !== 'all' && r.dataset.g !== b.dataset.f
})

// pricing: ticked features print on the receipt, hours add up
const boxes = $$('.menu input')
const receipt = () => {
  const on = boxes.filter(b => b.checked)
  $('#rLines').innerHTML = on.length ? on.map(b => `<li><span>${b.dataset.n}</span><span class="mono">${b.dataset.h} h</span></li>`).join('') : '<li class="r-empty">Tick the features you need.</li>'
  $('#rHours').textContent = on.reduce((s, b) => s + +b.dataset.h, 0)
}
for (const b of boxes) b.addEventListener('change', receipt)
receipt()

// FAQ: a tab list. Click or arrow keys pick the question; the answer shows on the right.
const tabs = $$('.qa-list [role=tab]')
const pick = i => tabs.forEach((t, j) => {
  t.setAttribute('aria-selected', i === j); t.tabIndex = i === j ? 0 : -1
  $(`#qp${j}`).hidden = i !== j
})
tabs.forEach((t, i) => {
  t.addEventListener('click', () => pick(i))
  t.addEventListener('keydown', e => {
    const k = { ArrowDown: 1, ArrowRight: 1, ArrowUp: -1, ArrowLeft: -1 }[e.key]
    if (!k) return
    e.preventDefault(); const n = (i + k + tabs.length) % tabs.length; pick(n); tabs[n].focus()
  })
})

// book: check the four fields, then thank them by name. No calendar.
const form = $('#book form'), done = $('#book .done')
const esc = s => s.replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c])
form.addEventListener('submit', e => {
  e.preventDefault()
  let ok = true
  for (const f of form.querySelectorAll('input, textarea')) {
    const v = f.value.trim(), bad = !v || (f.type === 'email' && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))
    f.closest('.field').classList.toggle('err', bad); if (bad) ok = false
  }
  if (!ok) return
  form.hidden = true
  done.innerHTML = `<div class="done-ico" aria-hidden="true">✓</div><p class="d-t">Thanks, ${esc(form.first.value.trim())}.</p><p>We'll email you at ${esc(form.email.value.trim())} to set up your 30-minute call.</p>`
  done.hidden = false
})
for (const f of form.querySelectorAll('input, textarea')) f.addEventListener('input', () => f.closest('.field').classList.remove('err'))

startStage({ ...shapes, EXTENTS })
